# Контрольные задачи по дисциплине СиАОД №1
## Выполнил студент группы БСТ1903 Смоляков И.В.
### Задача 1. «Треугольник с максимальным периметром»
Массив A состоит из целых положительных чисел ­ длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно
составить треугольник с положительной площадью ­ функция возвращает 0

In [1]:
from math import sqrt

def biggestPer(arr):
    biggest = 0
    for a in range(len(arr)-2):
        for b in range(a+1, len(arr)-1):
            for c in range(b+1, len(arr)):
                p = (arr[a] + arr[b] + arr[c]) / 2
                S2 = p * (p - arr[a]) * (p - arr[b]) * (p - arr[c])
                if S2 <= 0:
                    continue
                S = sqrt(S2)
                perim = arr[a] + arr[b] + arr[c]
                if perim > biggest:
                    biggest = perim
    return biggest


print(biggestPer([2,1,2]))
print(biggestPer([1,2,1]))
print(biggestPer([3,2,3,4]))
print(biggestPer([3,6,2,3]))

5
0
10
8


### Задача 2. «Максимальное число»
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы
вместе они образовали максимально возможное число.
Замечание: Результат может быть очень большим числом, поэтому представьте его как
string, а не integer.

In [1]:
def maxNum(arr):
    def is_a_bigger_than_b(a, b):
        ab = int(str(a) + str(b))
        ba = int(str(b) + str(a))
        if ab > ba:
            return True
        else:
            return False
    
    def sortArr(arr):
        for i in range(len(arr) - 1):
            biggest = i
            for j in range(i + 1, len(arr)):
                if not is_a_bigger_than_b(arr[biggest], arr[j]):
                    biggest = j
            arr[i], arr[biggest] = arr[biggest], arr[i]
    
    sortArr(arr)
    return ''.join(str(e) for e in arr)


print(maxNum([10,2]))
print(maxNum([3,30,34,5,9]))
print(maxNum([1]))
print(maxNum([10]))

210
9534330
1
10


### Задача 3. «Сортировка диагоналей в матрице»
Дана матрица mat размером m * n, значения ­ целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [3]:
import numpy
def sortDiag(matrix):
    for i in range(len(matrix)):
        diag = []
        r = i
        c = 0
        while True:
            try:
                diag.append(matrix[r][c])
                r += 1
                c += 1
            except IndexError:
                break
        diag.sort()
        r = i
        c = 0
        for j in range(len(diag)):
            matrix[r][c] = diag[j]
            r += 1
            c += 1
    
    for i in range(1, len(matrix[0])):
        diag = []
        r = 0
        c = i
        while True:
            try:
                diag.append(matrix[r][c])
                r += 1
                c += 1
            except IndexError:
                break
        diag.sort()
        r = 0
        c = i
        for j in range(len(diag)):
            matrix[r][c] = diag[j]
            r += 1
            c += 1
    
    return matrix

mat = numpy.array([[3, 3, 1, 1], [2, 2, 1, 2], [1, 1, 1, 2]], dtype=int)
print(mat)
print(sortDiag(mat), "\n")

mat = numpy.array([[11, 25, 66, 1, 69, 7], [23, 55, 17, 45, 15, 52], [75, 31, 36, 44, 58, 8], [22, 27, 33, 25, 68, 4], [84, 28, 14, 11, 5, 50]], dtype=int)
print(mat)
print(sortDiag(mat), "\n")

[[3 3 1 1]
 [2 2 1 2]
 [1 1 1 2]]
[[1 1 1 1]
 [1 2 2 2]
 [1 2 3 3]] 

[[11 25 66  1 69  7]
 [23 55 17 45 15 52]
 [75 31 36 44 58  8]
 [22 27 33 25 68  4]
 [84 28 14 11  5 50]]
[[ 5 17  4  1 52  7]
 [11 11 25 45  8 69]
 [14 23 25 44 58 15]
 [22 27 31 36 50 66]
 [84 28 75 33 55 68]] 

