# Курсовая работа по дисциплине СиАОД

## Выполнил студент группы БСТ1903 Смоляков И.В.

### Задача 1 «Шарики и стрелы»

Некоторые сферические шарики распределены по двухмерному пространству. Для каждого шарика даны x-координаты начала и конца его горизонтального диаметра. Так как пространство двумерно, то y-координаты не имеют значения в данной задаче. Координата Xstart всегда меньше Xend. Стрелу можно выстрелить строго вертикально (вдоль y-оси) из разных точек x-оси. Шарик с координатами Xstart и Xend уничтожается стрелой, если она была выпущена из такой позиции x, что Xstart ⩽ x ⩽ Xend. Когда стрела выпущена, она летит в пространстве бесконечное время (уничтожая все шарики на пути). Дан массив points, где points[i] = [Xstart, Xend]. Напишите функцию, возвращающую минимальное количество стрел, которые нужно выпустить, чтобы уничтожить все шарики.

In [1]:

def findMinArrowShots(points):
        if len(points) == 0:
            return 0
        points.sort(key = lambda a:a[1])
        arrows = 1
        curr = points[0]
        for balloon in points:
            if curr[1] < balloon[0]:
                curr = balloon
                arrows += 1
        return arrows
    
print("[[10, 16],[2,8],[1,6],[7,12]] -->", findMinArrowShots([[10,16], [2,8], [1,6], [7,12]]))
print("[[1,2],[3,4],[5,6],[7,8]] -->", findMinArrowShots([[1,2],[3,4],[5,6],[7,8]]))
print("[[1,2],[2,3],[3,4],[4,5]] -->", findMinArrowShots([[1,2],[2,3],[3,4],[4,5]]))
print("[[1,2]] -->", findMinArrowShots([[1,2]]))
print("[[2,3],[2,3]] -->", findMinArrowShots([[2,3],[2,3]]))


[[10, 16],[2,8],[1,6],[7,12]] --> 2
[[1,2],[3,4],[5,6],[7,8]] --> 4
[[1,2],[2,3],[3,4],[4,5]] --> 2
[[1,2]] --> 1
[[2,3],[2,3]] --> 1


## Задача 2 «Стопки монет»¶

На столе стоят 3n стопок монет. Вы и ваши друзья Алиса и Боб забираете стопки монет по следующему алгоритму:

1.Вы выбираете 3 стопки монет из оставшихся на столе

2.Алиса забирает себе стопку с максимальным количеством монет.

3.Вы забираете одну из двух оставшихся стопок.

4.Боб забирает последнюю стопку.

5.Если еще остались стопки, то действия повторяются с первого шага.


Дан массив целых положительных чисел piles. Напишите функцию, возвращающую максимальное число монет, которое вы можете получить.

In [2]:
import random

def maxCoins(arr):
    you = 0
    while len(arr) > 0:
        threeCoins = []
        for i in range(2):
            threeCoins.append(arr.pop(arr.index(max(arr))))
        threeCoins.append(arr.pop(arr.index(min(arr))))
        you += threeCoins[1]
    return you

print(maxCoins([2, 4, 1, 2, 7, 8]))
print(maxCoins([2, 4, 5]))
print(maxCoins([9, 8, 7, 6, 5, 1, 2, 3, 4]))

9
4
18


## Задача 3. «Объединение отрезков»

Дан массив отрезков intervals, в котором intervals[i] = [starti, endi], некоторые отрезки могут пересекаться. Напишите функцию, которая объединяет все пересекающиеся отрезки в один и возвращает новый массив непересекающихся отрезков.

In [3]:

def concate_intervals(intervals):
    result = []
    intervals.sort()
    for interval in intervals:
        if result == [] or result[-1][1] < interval[0]:
            result.append(interval)
        else:
            result[-1][1] = max(result[-1][1], interval[1])
    return result

print(concate_intervals([[1,3],[2,6],[8,10],[15,18]]))
print(concate_intervals([[1,4],[4,5]]))

[[1, 6], [8, 10], [15, 18]]
[[1, 5]]


## Задача 4. «Треугольник с максимальным периметром»
Массив A состоит из целых положительных чисел ­ длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью ­ функция возвращает 0

In [4]:
from math import sqrt

def biggestPer(arr):
    biggest = 0
    for a in range(len(arr)-2):
        for b in range(a+1, len(arr)-1):
            for c in range(b+1, len(arr)):
                p = (arr[a] + arr[b] + arr[c]) / 2
                S2 = p * (p - arr[a]) * (p - arr[b]) * (p - arr[c])
                if S2 <= 0:
                    continue
                S = sqrt(S2)
                perim = arr[a] + arr[b] + arr[c]
                if perim > biggest:
                    biggest = perim
    return biggest


print(biggestPer([2,1,2]))
print(biggestPer([1,2,1]))
print(biggestPer([3,2,3,4]))
print(biggestPer([3,6,2,3]))

5
0
10
8


## Задача 5. «Максимальное числ
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число. Замечание: Результат может быть очень большим числом, поэтому представьте его как string, а не integer.

In [5]:
def maxNum(arr):
    def bigger(a, b):
        ab = int(str(a) + str(b))
        ba = int(str(b) + str(a))
        if ab > ba:
            return True
        else:
            return False
    
    def sortArr(arr):
        for i in range(len(arr) - 1):
            biggest = i
            for j in range(i + 1, len(arr)):
                if not bigger(arr[biggest], arr[j]):
                    biggest = j
            arr[i], arr[biggest] = arr[biggest], arr[i]
    
    sortArr(arr)
    return ''.join(str(e) for e in arr)


print(maxNum([10,2]))
print(maxNum([3,30,34,5,9]))
print(maxNum([1]))
print(maxNum([10]))

210
9534330
1
10



## Задача 6. «Сортировка диагоналей в матрице»
 Дана матрица mat размером m * n, значения ­ целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [6]:
import numpy
def sortDiag(matrix):
    for i in range(len(matrix)):
        diag = []
        r = i
        c = 0
        while True:
            try:
                diag.append(matrix[r][c])
                r += 1
                c += 1
            except IndexError:
                break
        diag.sort()
        r = i
        c = 0
        for j in range(len(diag)):
            matrix[r][c] = diag[j]
            r += 1
            c += 1
    
    for i in range(1, len(matrix[0])):
        diag = []
        r = 0
        c = i
        while True:
            try:
                diag.append(matrix[r][c])
                r += 1
                c += 1
            except IndexError:
                break
        diag.sort()
        r = 0
        c = i
        for j in range(len(diag)):
            matrix[r][c] = diag[j]
            r += 1
            c += 1
    
    return matrix

mat = numpy.array([[3, 3, 1, 1], [2, 2, 1, 2], [1, 1, 1, 2]], dtype=int)
print(mat)
print(sortDiag(mat), "\n")

mat = numpy.array([[11, 25, 66, 1, 69, 7], [23, 55, 17, 45, 15, 52], [75, 31, 36, 44, 58, 8], [22, 27, 33, 25, 68, 4], [84, 28, 14, 11, 5, 50]], dtype=int)
print(mat)
print(sortDiag(mat), "\n")

[[3 3 1 1]
 [2 2 1 2]
 [1 1 1 2]]
[[1 1 1 1]
 [1 2 2 2]
 [1 2 3 3]] 

[[11 25 66  1 69  7]
 [23 55 17 45 15 52]
 [75 31 36 44 58  8]
 [22 27 33 25 68  4]
 [84 28 14 11  5 50]]
[[ 5 17  4  1 52  7]
 [11 11 25 45  8 69]
 [14 23 25 44 58 15]
 [22 27 31 36 50 66]
 [84 28 75 33 55 68]] 



## Задача 7. Первая задача на строки 

Даны две строки: s1 и s2 с одинаковым размером, проверьте, может ли некоторая перестановка строки s1 “победить” некоторую перестановку строки s2 или наоборот. Строка x может “победить” строку y (обе имеют размер n), если x[i]> = y [i] (в алфавитном порядке) для всех i от 0 до n-1.

In [7]:
def strFight (s1,s2):
    if len(s1) != len(s2) or len(s1) > 10**5 or len(s2) > 10**5:
        raise ValueError
    count1 = 0
    count2 = 0
    s1 = ''.join(sorted(s1))
    s2 = ''.join(sorted(s2))
    for i in range(len(s1)):
        if s1[i] >= s2[i]:
            count1 += 1
        if s1[i] <= s2[i]:
            count2 += 1
    if count1 == len(s1) or count2 == len(s1):
        return True
    return False
print(strFight ("abc", "acd"))

True


## Задача 8. Вторая задача на строки
Дана строка s, вернуть самую длинную полиндромную подстроку в s.

In [8]:
def isPalindrome(word):
    word = word.lower()
    word1 = ''.join(reversed(word))
    if word1 == word:
        return True
    return False

def longestPalindrome(s):
    max = 1
    ans = s[0]
    for a in range(len(s) - 1):
        word = s[a]
        for b in range(a+1, len(s)):
            word += s[b]
            if isPalindrome(word):
                l = len(word)
                if l > max:
                    max = l
                    ans = word
    return ans
print(longestPalindrome("babad"))
print(longestPalindrome("cbbd"))

bab
bb


## Задача 9. Третья задача на строки 

Вернуть количество отдельных непустых подстрок текста, которые могут быть записаны как конкатенация некоторой строки с самой собой (т.е. она может быть записана, как a + a, где a - некоторая строка).

In [9]:
def isConcatenationPossible(word,s):
    for a in range(len(s) - 1):
        guess = s[a]
        for b in range(a+1, len(s)):
            guess += s[b]
            if guess == word * 2:
                return True
    return False


def numOfConcatenationStrings(s):
    count = 0
    mem = []
    for a in range(len(s) - 1):
        guess = s[a]
        if isConcatenationPossible(guess,s):
                if guess not in mem:
                    count += 1
                    mem.append(guess)
        for b in range(a+1, len(s)):
            guess += s[b]
            if isConcatenationPossible(guess,s):
                if guess not in mem:
                    count += 1
                    mem.append(guess)
    return count
print (numOfConcatenationStrings("abcabcabc"))

3


# Вывод


В ходе курсовой работы мы научились решать различные задачи при помощи языка программирования Python 3.